// lib/email_format.mjs

/**
 * Purpose:
 * Produce a clean, professional email subject + body for the daily lead report.
 *
 * Inputs:
 * - metro (string)
 * - date (string, e.g. "2026-02-12")
 * - leads: normalized leads (preferred) OR scored candidates (fallback)
 *
 * Output:
 * - { subject, bodyText }
 *
 * Notes:
 * - No network calls
 * - No Gmail sending here (pure formatting)
 * - Keeps it simple + readable
 */

function clean(s) {
  if (s == null) return "";
  return String(s).replace(/\s+/g, " ").trim();
}

function asLine(label, value) {
  const v = clean(value);
  if (!v) return null;
  return `${label}: ${v}`;
}

function formatNormalizedLead(lead, idx) {
  // Expected fields:
  // fingerprint, name, main_phone, address, website, description, reason_for_inclusion
  const lines = [];

  const name = clean(lead.name) || clean(lead.website) || "Unknown";
  lines.push(`${idx + 1}. ${name}`);

  const maybe = [
    asLine("Website", lead.website),
    asLine("Phone", lead.main_phone),
    asLine("Address", lead.address),
    asLine("Description", lead.description),
    asLine("Why", lead.reason_for_inclusion),
  ].filter(Boolean);

  for (const l of maybe) lines.push(`   ${l}`);

  return lines.join("\n");
}

function formatScoredCandidate(c, idx) {
  // Fallback shape from selected_candidates.json:
  // fingerprint, score, reasons[], title, url, description, host
  const lines = [];
  lines.push(`${idx + 1}. ${clean(c.title) || "Unknown"}`);

  const maybe = [
    asLine("URL", c.url),
    asLine("Host", c.host),
    asLine("Score", c.score),
    c?.reasons?.length ? `   Reasons: ${c.reasons.slice(0, 6).join(", ")}` : null,
    clean(c.description) ? `   Snippet: ${clean(c.description)}` : null,
  ].filter(Boolean);

  for (const l of maybe) lines.push(l.startsWith("   ") ? l : `   ${l}`);

  return lines.join("\n");
}

export function formatLeadsEmail({ date, metro, leads, mode }) {
  const d = clean(date) || new Date().toISOString().slice(0, 10);
  const m = clean(metro) || "Metro";

  const kind = mode === "normalized" ? "Leads" : "Candidates";
  const subject = `Daily ${kind} (${m}) — ${d}`;

  const header = [
    `Daily ${kind} Report`,
    `Date: ${d}`,
    `Metro: ${m}`,
    `Count: ${Array.isArray(leads) ? leads.length : 0}`,
    "",
  ].join("\n");

  const items = (leads ?? []).map((x, idx) =>
    mode === "normalized" ? formatNormalizedLead(x, idx) : formatScoredCandidate(x, idx)
  );

  const footer = [
    "",
    "---",
    "Generated by OpenClaw POC (deterministic search + scoring; optional LLM normalization).",
  ].join("\n");

  return {
    subject,
    bodyText: header + items.join("\n\n") + footer,
  };
}

